require:
  - rubocop-rake
  - rubocop-rspec
AllCops:
  NewCops: enable
Metrics/AbcSize:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
